### PR TITLE
Added the Multivariate Analysis

### PR DESCRIPTION
**Pull request by soumya997**
Added the multivariate analysis notebook and the python file.

### CODE REVIEW

**Comment by soumya997** [comment]
I just added two files ( multivariate analysis notebook and the  multivariate analysis python file)
but it is showing 6 file changes.
I pushed from the same branch as before "soupyadip1", is it because of that?

**Comment by Nibba2018** [comment]
Hey @soumya997 , You need to rebase your branch with the updated DSC-IEM repo changes. In order to do that you need to execute the following command:
`git rebase dsc-iem/master`
assuming that you are currently in this branch and `dsc-iem` points to the upstream repo.

**Comment by soumya997** [comment]
So first need to switch to master branch then I have to execute `git rebase dsc-iem/master`, is this right @Nibba2018 ?

**Comment by Nibba2018** [comment]
@soumya997 No need to switch to master branch execute it in your current branch.

**Comment by soumya997** [comment]
`git remote add upstream https://github.com/dsc-iem/AI-Hacktoberfest.git`
is this the command to make dsc-iem point to upstream @Nibba2018 ?

**Comment by Nibba2018** [comment]
@soumya997 its a bit different:
`git remote add dsc-iem <link>`

**Comment by Nibba2018** [comment]
@soumya997 , You might face merge conflicts while rebasing. We continue this conversation on discord.

**Comment by soumya997** [comment]
ok, just let me try this once

**Comment by soumya997** [comment]
it is looking like this. Now do I have to push the changes again @Nibba2018 ?
<br>
image

**Comment by Nibba2018** [comment]
@soumya997 can talk about this on discord?

**Comment by soumya997** [comment]
ok

**Comment by soumya997** [comment]
Hey @BALaka-18 @Nibba2018 is there any problem in my PR?

**Comment by Nibba2018** [comment]
LGTM, Merging!

**Pull request merged**
